### ISSUE TITLE
user-registration-sw image can't pull

### ISSUE THREAD

**Issue by RunningMartin** [automatiko-io/automatiko-examples#45]
hi, when i finish the example **user-registration-sw**，i meet an error：
```
Error response from daemon: pull access denied for mswiderski/user-registration-sw, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```
and I can't find the image from docker hub.

**Comment by RunningMartin** [comment]
> you should use `automatiko/user-registration-sw` instead of the `mswiderski` repository.
> 
> Could you please give it a try with that one?
> 
> In addition, let me know when it references `mswiderski` so I will fix it to point to `automatiko`

very good，thank you

**Comment by mswiderski** [comment]
I assume this solved the issue so I am closing it. in case there are still problems feel free to reopen.
