### ISSUE TITLE
Using an archived Kafka repo

### ISSUE THREAD

**Issue by pguerin3** [automatiko-io/automatiko-examples#51]
I'm having issues running the Orders example.
The prerequisite is to run a Kafka/Zookeeper container, but notice that this container doesn't work for me and is no longer maintained (according to the issues).
[https://github.com/spotify/docker-kafka/issues](https://github.com/spotify/docker-kafka/issues)
Maybe you can correct the install instructions for the Orders example.

**Comment by mswiderski** [comment]
it's good point to update the docs to not refer to Spotify Kafka anymore.

Have you ran into problems using other broker like for instance [redpanda](https://docs.redpanda.com/docs/get-started/quick-start/?quickstart=docker#deploy-redpanda)?

**Comment by mswiderski** [comment]
updated readme files with link to Redpanda docs as an implementation of the broker and verified that it works as expected with it. Documentation (docs.automatiko.io) will be updated with next release.

Thanks for pointing it out!!!

**Comment by pguerin3** [comment]
To get the example to work I had to stop the RedPanda console, as it was occupying port 8080.
So then the example was able to work with the console stopped, but then I was getting the warnings:
```
2023-03-05 06:19:12,954 WARN  [org.apa.kaf.cli.NetworkClient] (smallrye-kafka-consumer-thread-1) [Consumer clientId=kafka-consumer-customers, groupId=Orders-consumer] Connection to node -1 (localhost/127.0.0.1:9092) could not be established. Broker may not be available.
```

**Comment by pguerin3** [comment]
I'm also getting:
```
2023-03-05 06:29:28,947 WARN  [org.apa.kaf.cli.NetworkClient] (smallrye-kafka-consumer-thread-1) [Consumer clientId=kafka-consumer-customers, groupId=Orders-consumer] Bootstrap broker localhost:9092 (id: -1 rack: null) disconnected
```

**Comment by mswiderski** [comment]
you need to make sure you redpanda instance is bound to a IP of your OS and not localhost as when you run orders container it must not use localhost as address of Kafka.

That main means you need to change the localhost in docker-compose.yaml that you use for redpanda, see example with `external://192.168.100.23:19092` as IP:

````
      - --advertise-kafka-addr internal://redpanda-0:9092,external://192.168.100.23:19092
      - --pandaproxy-addr internal://0.0.0.0:8082,external://0.0.0.0:18082
      # Address the broker advertises to clients that connect to PandaProxy.
      - --advertise-pandaproxy-addr internal://redpanda-0:8082,external://192.168.100.23:18082
      - --schema-registry-addr internal://0.0.0.0:8081,external://0.0.0.0:18081
      # Redpanda brokers use the RPC API to communicate with eachother internally.
````

so that IP needs to be IP of your machine so it can be reached from within the docker container that runs the orders example.
